server:
  port: 8080

spring:
  application:
    name: Jira
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/jiradb
    username: admin
    password: password

